import React from 'react'
import {Container, Row, Col} from 'react-bootstrap';

const About = () => {
  return (
    <>
        <Container style = {{marginTop : '50px'}}>
            <h1> Qui sommes-nous ?</h1>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi obcaecati accusantium dignissimos quidem dicta neque quas, iste nobis deleniti dolorem corporis, magni at quibusdam possimus earum vero a nihil dolores quis officia autem. Ab ratione explicabo hic, rem illum est nemo, culpa ea adipisci autem obcaecati dolorem. Sequi, accusamus alias veniam reprehenderit, sed possimus nulla delectus neque libero quis aperiam obcaecati dolores nisi. Voluptas doloribus quam neque, reprehenderit doloremque asperiores inventore quibusdam dolores fuga quisquam nostrum totam iure quis ratione! Omnis nihil delectus debitis laboriosam unde numquam autem reprehenderit totam in, fuga id tenetur quidem ipsum assumenda possimus repellat deleniti, ab aliquid voluptatem voluptatum excepturi iusto, cumque nesciunt! Et nostrum repellat minus facilis officia totam nemo sequi possimus? Architecto dolores eius, cupiditate dicta tempora officiis debitis soluta in sed cumque, dolorem id. Vitae natus voluptas quo rerum laboriosam blanditiis. Commodi, mollitia autem ipsum explicabo fugiat, magni nulla dolorum facere exercitationem saepe temporibus iure tenetur, quasi quibusdam amet! Animi omnis repellendus totam aut optio! Voluptatum delectus odit sed unde nisi deserunt corporis praesentium eos quia iusto rerum dolorem consequatur ad totam inventore vitae quas quibusdam facere, nostrum ea at minima officia! Earum atque in commodi quis provident dignissimos voluptatem, alias corrupti.</p>
            <h1> Notre spécialité </h1>
            <Row>
                <Col md={6}>
                    <p> Lorem ipsum dolor sit amet consectetur, adipisicing elit. Molestiae sit repudiandae ea saepe labore. Exercitationem laudantium alias necessitatibus in cumque ex et debitis rem, repellat voluptatum voluptates libero praesentium nesciunt harum cum aliquid quo ipsum officia maiores earum! At excepturi labore alias fugiat earum, sed tenetur voluptatem eos quidem expedita sapiente est aspernatur dicta provident perferendis commodi architecto. Fuga voluptate est modi repudiandae rem, accusamus eum, eligendi deserunt iste iusto ea totam vero, unde natus. Mollitia facilis nisi cumque ipsum nulla maiores tenetur aspernatur atque non, ratione, repellendus maxime nam exercitationem assumenda animi placeat itaque enim odio temporibus, quas doloremque quis reprehenderit! Voluptatibus non vel, blanditiis illum, quae nihil a qui repudiandae eaque ut velit impedit. Possimus quo quae dolorum illo voluptatem tempore error nulla consectetur. Deleniti dolore odit in, praesentium, minus dignissimos nam adipisci incidunt enim explicabo molestiae cumque atque? Nisi nulla officiis eum est quibusdam. Nam, velit? Deleniti explicabo quo distinctio doloremque commodi, quaerat eveniet laborum labore saepe quasi possimus, architecto molestias modi maxime sed earum eaque dolorem quibusdam quam minima ea animi. Ducimus similique obcaecati consequatur vero. Ad excepturi vitae aspernatur natus ipsa deserunt optio itaque temporibus odio? Totam voluptate quod ipsa veritatis consequatur asperiores voluptas in.</p>
                </Col>
                <Col md={6}>
                    <p> Lorem ipsum dolor sit amet consectetur, adipisicing elit. Commodi iusto consectetur, sapiente aut provident reprehenderit exercitationem ab! Hic sed deleniti cupiditate voluptatibus repudiandae fugiat provident sapiente adipisci, tempore, aliquam possimus sit itaque reprehenderit maiores neque consectetur quas repellat nostrum modi ab, at minima labore. Placeat autem delectus obcaecati eos sunt, ad nobis sit fugit iure eaque, nam aspernatur officiis laboriosam ullam ipsa ea, cumque voluptates sed odit ex ipsum eius quibusdam! Id vitae commodi temporibus voluptatum eum nulla tenetur consequuntur libero voluptatem vel beatae tempora necessitatibus quisquam quidem, facilis, fugiat molestias earum consectetur repudiandae dolor laboriosam? Ut veniam voluptatum laudantium, blanditiis quis eaque, corrupti quidem doloremque alias nesciunt facere, in nobis ex neque ad repudiandae vel accusantium asperiores sunt! Dolore repudiandae quos eos nam alias dicta ullam error quae. Ab architecto commodi provident nostrum? Eligendi porro, debitis ullam rem possimus, laboriosam aut sapiente, perferendis velit veniam fugiat. Facere amet quasi fugit neque at assumenda consequatur eligendi excepturi, molestiae aliquid nam blanditiis id voluptatem quidem a quae accusamus dolorum repudiandae omnis dolor? Quos inventore, necessitatibus ipsum aspernatur neque maiores eum assumenda earum magnam hic enim? Quaerat, laudantium voluptatibus. Officia quo exercitationem sapiente ullam temporibus consectetur voluptate, cupiditate, reiciendis voluptatum deleniti error.</p>
                </Col>
            </Row>
            <Row>
                <h1> Le Chef </h1>
                <Col md={3}>
                    <p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit earum tempore qui ad adipisci quaerat, distinctio veritatis perferendis totam, eius in ipsum voluptas sequi, error tenetur voluptatibus dicta vero deleniti sint. Recusandae commodi optio, rerum animi deleniti dolores consequuntur odio nemo nobis laborum quaerat non magnam aperiam nesciunt, deserunt ea quos corrupti consectetur! Expedita veritatis totam quae! Impedit quasi cum assumenda aspernatur soluta recusandae? Totam iure voluptas delectus at sequi quaerat aliquid eos. Tempora aliquid perferendis facilis dolores quaerat? Earum illum quis natus dolores pariatur quibusdam magni, quas harum, deserunt doloribus voluptas ullam adipisci! Expedita pariatur laborum quia consequatur provident?</p>
                </Col>
                <Col md={3}>
                    <p> Lorem ipsum, dolor sit amet consectetur adipisicing elit. Molestias iusto mollitia accusamus quod ipsum. Voluptas dolores nobis a pariatur ad dolor ratione accusamus nulla eveniet aliquam! Incidunt quos repudiandae quis eligendi sequi veniam, rerum reprehenderit obcaecati optio distinctio alias saepe, non consequatur error eaque nobis delectus sapiente perferendis odit doloremque ab! Nam aliquam ducimus doloremque laboriosam ex minima, eveniet sapiente, nesciunt optio inventore aut debitis, saepe cumque non quibusdam ad. Culpa, reprehenderit cumque! Ullam fuga magni quos consequuntur non exercitationem voluptatem iusto, architecto, earum similique libero voluptas est. Repudiandae non quod iure delectus officiis placeat repellendus hic eum suscipit expedita.</p>
                </Col>
                <Col md={3}>
                    <p> Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repudiandae dolorum, cum doloribus commodi incidunt minus eveniet numquam esse praesentium repellendus, ea sequi hic nesciunt beatae consequuntur deleniti quidem! Obcaecati voluptatum eaque officiis sed doloremque laborum. Quia ea dicta, quas placeat dignissimos itaque alias illo perferendis culpa adipisci rerum saepe aliquam officiis illum pariatur eligendi repellat cumque enim deserunt laboriosam maiores voluptate. Doloribus fugit laudantium animi error neque esse eius officia at ratione similique, voluptatibus ea, molestiae omnis, ducimus vitae eos nam iste commodi culpa qui quia. Ut cupiditate sint eius autem. Reiciendis, sit? Officiis non harum, blanditiis ad atque quam.</p>
                </Col>
                <Col md={3}>
                    <p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore quas possimus sed sunt consectetur? Quod asperiores sapiente et laboriosam, doloribus tempora repellat cum? Deserunt dolores unde aperiam, quia exercitationem quibusdam velit pariatur, consectetur harum saepe, itaque rerum! Ipsa aliquid itaque porro ad beatae exercitationem quis quas fugiat maxime dolore quo tempora vero nesciunt deserunt natus, officiis saepe provident rerum nulla doloremque accusantium. Voluptatibus porro, sit eius laborum saepe repudiandae repellat vitae blanditiis, doloribus consequuntur distinctio mollitia laudantium incidunt magni expedita? Dolore veritatis amet id quaerat, quis error, tenetur doloremque, incidunt possimus mollitia ab saepe voluptas eius eos cum est rem!</p>
                </Col>
            </Row>
        </Container>
    </>
  )
}

export default About